### ISSUE TITLE
start Alacritty from CRTL+ALT+t

### ISSUE THREAD

**Issue by khebbie** [basecamp/omakub#119]
First of all: what a cool project - thx for all the hard work.

In ubuntu the shortcut CTRL+ALT+T starts the terminal, and it works fine in omakub, however since the alacritty is the default terminal, maybe the shortcut should start alacritty.

**Comment by khebbie** [comment]
it seems these commands does the trick
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator $(which alacritty) 50
sudo update-alternatives --config x-terminal-emulator

I have not yet taken the time to understand how omakub is structured, but might look into it.

**Comment by dhh** [comment]
Yeah, I've been going back and forth over this. I'm not sure it's worth changing, because you may still want the gnome terminal in some circumstances. And in any case, we've standardized on the alt+[number] and shift+alt+[number] as hotkeys for switching between and starting apps. So think that'll do for now. Of course totally fine for anyone to make this alteration after the fact!
