### ISSUE TITLE
Give an option to customize the list of istalled applications

### ISSUE THREAD

**Issue by rdanilin** [basecamp/omakub#20]
It would be nice to have some customization for installed applications. For example install Firefox instead of Chrome. 

Maybe we can have a list of installed apps in text file loaded from external storage or git repository.

**Comment by dhh** [comment]
All substitutes are freely encouraged after the installation is done. But there will be no configuration available up front.

**Comment by krizzdev** [comment]
@dhh what about an optional non version controlled file omakub can check at installation, where we can exclude some app installs or include our own install scripts, which will be run.

Example: I like most of the preinstalled apps, but I don’t need Ruby or some other apps myself, because coming with a laravel PHP background.

Nonetheless I will built my scripts around it, if that’s not an option. Thanks for the effort 🙏

**Comment by dhh** [comment]
I could imagine some back-of-the-house power option for that. Like if you have ~/.config/omakub/skip-installs or something that's just a list of the .sh files you don't want? Do explore that. Though I think for most people, having an easy way to uninstall after the fact will be better.
