### ISSUE TITLE
Unable to Uninstall Omakub

### ISSUE THREAD

**Issue by dinesh8368** [basecamp/omakub#283]
I’m having trouble uninstalling the Omakub from my system. I’ve tried using few commands but I’m still stuck.
Could someone please guide me through the uninstallation process? Any help would be greatly appreciated!

**Comment by florentdestremau** [comment]
![no return journey](https://y.yarn.co/f2e7f37f-67e2-40bf-9ffd-f5ccdea904a6_text.gif)

It's not really thought to be uninstallable as a whole at this time (and as you're supposed to use it on a fresh ubuntu, you're not so far away to reset again).

**Comment by crobbo** [comment]
I managed to restore my desktop by doing this:

First back up the `.local` folder (so you can restore it if anything goes wrong)

`cp -r .local .local_backup` 

Then remove omakub from the shared folder:

`rm -rf .local/share/omakub` 

This appears to restore back to the default ubuntu desktop. Obviously it will not remove the installed apps, etc.

**Comment by dhh** [comment]
You're better off just reinstalling if you don't want Omakub.

**Comment by VGerris** [comment]
> You're better off just reinstalling if you don't want Omakub.

First of all, I am a great fan of your work and spirit, thank you for sharing knowledge and being vocal :)!

May I suggest to put this in the Omakub installation guide beginning as a warning if so ?
I experienced some really strange issues with my terminal with the font looking funny and commands like 'ls -lrta' would throw some error about t not existing.

I resolved it by restoring the default monospace font to monospace 12 and :
sudo apt-get install --reinstall ubuntu-desktop # not sure if that did anything useful.

Now I have a working terminal and a funky desktop wallpaper !

I still seem to have some issues with bash completion, but that must be in once of the startup files.

I suggest to highlight the main changes or do an uninstall script for who wants it, I can say this is not the perfect setup for me but I am greatful that you shared it, great inspiration for doing my own ( if ever ).
Thank you!

**Comment by VGerris** [comment]
Thank you for the quick reply!
I meant some kind of indication that it may be challenging to restore.
I understand how you use it and your intention of clean and redo, I just have a lot of local things installed, stored and configured that I don't know how to script easily ( and I want to just use the storage on the laptop ).

It would be much better to just backup my home directory and reinstall and restore I guess, but I also have multiboot that messes with Grub and in general I barely ever reinstall, because it 'just works'.

To me the changes made may be challenging for starters and as such a warning of not easy to return may be useful.
I have been using Linux for many years on the desktop, so I was able to figure it out.
I did use a lot of the installer, I just got issues with the fonts in the Terminal,

Thank you for the inspiration!
