### ISSUE TITLE
Ensure compatibility with Pop! OS

### ISSUE THREAD

**Issue by dhh** [basecamp/omakub#61]
Pop! is the default on System76. Would be great if the Omakub setup could produce the same environment there as it does on vanilla Ubuntu. What do we need to change to get there?

**Comment by iljo-dp** [comment]
asfaik pop-os ships gnome 42 and uses a lot of their own extensions and stuff, so I'm not sure that modern extensions and stuff would work here, but I'il be trying omakub on pop os soon, and I'il report back

**Comment by dhh** [comment]
Ah, okay. Let's see if it's possible to stretch there. But if not, that's also good information.

**Comment by blankRSD** [comment]
Even though they are currently using GNOME, Pop-os is moving to a completely new DE [Cosmic](https://blog.system76.com/post/cosmic-the-road-to-alpha). 

 So, it might be difficult to maintain UI compatibility, but apps and CLI can be done since under the hood it will still be using ubuntu & apt.

**Comment by adevade** [comment]
I believe that Pop!_OS 24.04 is shipping with their own new desktop environment Cosmic, but that may not matter? I'm relatively new to Linux on the desktop...

More info about Cosmic: https://news.itsfoss.com/pop-os-cosmic/

**Comment by dhh** [comment]
Ah yeah, once they go Cosmic, it'll have diverged too far.

**Comment by dhh** [comment]
I'm skeptical that's a compatible vision. The majority of the novel work here is about Gnome specific tweaks, extensions, hotkeys, whatever.

If all you wanted was the packages, you could boil this down to a single file.

**Comment by iljo-dp** [comment]
I think adding pop_os comparability isn't worth it, most stuff won't work atm, and the work to get it working will be all done gone once cosmic becomes the standard. And there isn't a lot that pop-os offers that you can't yourself add to ubuntu, the main things are the pop os custom apps, and the gui/driver install.
Imo not worth the work for omakub to also include pop_os support since it has a lot of older packages and would require a significant effort(way way more then adding arm support ;) )
