### ISSUE TITLE
Add omakub uninstall

### ISSUE THREAD

**Issue by dhh** [basecamp/omakub#62]
The default should be a no-configuration setup that includes a broad selection of what most people need.

But you should certainly be able to take things out of the box that you don't want.

Let's add a serious of uninstall scripts, so you can run "omakub uninstall" and pick any of the pieces you'd like to see removed.

**Comment by Areeba-Khaliq** [comment]
@dhh how can I completely remove the whole omakub?

**Comment by dhh** [comment]
Right now, there's no automated way of doing that. Would be happy to see a script added that does that, though.

**Comment by florentdestremau** [comment]
another aspect of this would be to have an interactive list of "apps" where you could uncheck the boxes to avoid install.

**Comment by TomJCoutts** [comment]
Personal opinion and there are many ways to approach this! I think the install should have everything to avoid complicating things and taking away from the "magic" of the one command and done 

Then after the fact if need to/want you can pick apart the stuff you don't need?

**Comment by 2KAbhishek** [comment]
For handling uninstallation we can utilize the existing scripts with an extra arg `-u/--uninstall`

Something like:

```bash
# Run uninstallers
for script in ~/.local/share/omakub/install/*.sh; do source $script -u; done
```

Then we can update scripts in the install directory with a check for args and reverse the operations done during install.

This will help with code organization, as install/uninstall scripts will be in the same file.

Another worthwhile change would be to have the `install` dir renamed to `setup` or something more appropriate

@TomJCoutts this may be helpful 😄

**Comment by 2KAbhishek** [comment]
I agree that having a separate uninstall directory might be simpler, but the reason I wanted to propose a shared file was so that we can see both the install and uninstall commands at the same time.

This may come in handy when debugging or with maintaining.

For example:

For a particular file, let's say bash, I know that the config file is named ~/.bashrc.bak

So while uninstalling I know which path and filename to use

We can even create shared variables like:

CONFIG_PATH: and BACKUP_FILE: etc. to aid in this.

Something I would again say will help with maintaining, but totally understand if the group wants to go the other direction :)

**Comment by dhh** [comment]
Appreciate that, but don't think it outweighs the simplicity of having 1 script do 1 thing.

**Comment by dhh** [comment]
Added this.
