### ISSUE TITLE
Zsh/fish? Additional tool suggestions

### ISSUE THREAD

**Issue by dennym** [basecamp/omakub#82]
Is there a reason why the choice went for plain bash when there is zsh/fish out there which open up so much more possibilities for configuration with their already existing config frameworks (e.g. oh-my-zsh)?

Unrelated:
I would like to suggest also autojump.sh and thefuck as default tools to be installed.

**Comment by csfh** [comment]
I think for simplicity's sake using Bash and focusing on great tooling for it may be the best for Omakub. Once we start going into different shells I think it'll greatly increase the complexity for other tools.

Everything ever added would have to work for all possible shells.

So far I find bash to do the job. Only thing I'm missing is more prompts and command line highlighting.

**Comment by dennym** [comment]
I kinda can understand that there is plenty of overhead with oh-my-zsh or similar frameworks but skipping them also this adds a lot of complexity down the road for omakub when trying to replicate for example aliases or just common plugins for default tools most people use.

Another example would be themes... So much work over decades went into making theming more accessible through frameworks and now we start from scratch again? It feels to me like going back to assembly and discard all advances that were made since then for the sake of simplicity :)

To be able to build a decent community around omakub to keep it maintained and evolving I believe it should not rely on too much "opinionated" .
Currently it is mostly for the use case of Basecamp and their ruby/node world and everyone else who is interested and a potential future contributer from other languages or stacks has to work around omakubs configuration and install scripts to leverage their tooling.

Just my 5cents since I tried to use omakubs but basically had to throw out half of the things and reconfigure my world of other languages to make them work. I will still keep an eye on it and cherry-pick some of the fine pieces for my setup. Thanks ❤️ 

_Feel free to close this if there are no more follow-up questions or arguments_

**Comment by dhh** [comment]
Omakub needs to focus on 1 answer the vast majority of options. That's the whole point. That we sidestep the paradox of choice by simply focusing on one choice. So we won't be going down the "do you want this shell or that". What I won't shut the door on entirely is using, say, zsh, INSTEAD of bash. But to be honest, I haven't seen a very compelling reason to just yet.

But opinionated is literally in the name of the project. It's Omakase Ubuntu. Chef's Choice Ubuntu. There's plenty of room for a million other projects to do things differently, but that's what this project is about. One set of great choices.
