### ISSUE TITLE
problem related to zellij when logging in after a fresh install

### ISSUE THREAD

**Issue by lvnilesh** [basecamp/omakub#9]
Thank you for omakub. 

This is a fresh install and I note this error

```
error found when loading .profile 

thread main panicked at zellij-client/src/os_input _output.rs:29.43 

could not get terminal attribute: ENOTTY 

as a result the session will not be configured correctly. You should fix the problem as soon as feasible.
```

**Comment by dhh** [comment]
Can you give some more details about your system? I haven't seen that one across everything I've looked at. Maybe @imsnif can help us figure out what's up.

**Comment by imsnif** [comment]
Seems like Zellij is being launched without a controlling terminal. I'm not aware of the particulars of the environment here, but this can for example happen if Zellij is launched from within a background script.

Any context on when we get this error? Every time a terminal is launched, or?

**Comment by imsnif** [comment]
So, a guess for now after looking around the repo a bit: if the conditional generated by [this command](https://github.com/basecamp/omakub/blob/11a66c5cb6cdd2c27c5751dea2d4b64b3ce80b18/defaults/bash/init#L4) is placed in a bash file that gets invoked outside of the Zellij context, this might be causing the error.

Since this setup comes pre-cooked with Alacritty, may I recommend having Alacritty launch Zellij directly rather than having it launched by bash? If my guess is correct this should resolve the issue.

This can be done like so in the Alacritty configuration:
```toml
[shell]
program = "zellij"
# args = ["-l", "welcome"] # optionally, if you'd like to start Zellij with a welcome screen to help manage sessions
```

**Comment by dhh** [comment]
We can definitely switch to that configuration, but there must be something else going on too. I've installed this setup on a bunch of machines, as have others, and not seen that error. But lemme try to switch over anyway!

**Comment by dhh** [comment]
Hmm, on second thoughts, don't love the idea of moving this into alacritty. Since if someone wanted to replace wezterm or kitty or whatever in its place, they'd have to deal with the zellij integration there too by hand. 

Let's see if we can't find what the actual issue is here. Doesn't seem widespread. Can you share more about your setup @lvnilesh? Are you running this in a wm of some kind or?

**Comment by dhh** [comment]
@lvnilesh Try the suggestion to have alacritty start zellij directly instead of via bash.

**Comment by lvnilesh** [comment]
This diff seems to resolve the issue.
```
diff --git a/defaults/alacritty.toml b/defaults/alacritty.toml
index cdb16b7..0654095 100644
--- a/defaults/alacritty.toml
+++ b/defaults/alacritty.toml
@@ -11,3 +11,7 @@ opacity = 0.97
 bindings = [
 { key = "F11", action = "ToggleFullscreen" }
 ]
+
+[shell]
+program = "zellij"
+# args = ["-l", "welcome"] # optionally, if you'd like to start Zellij with a welcome screen to help manage sessions
diff --git a/defaults/bash/init b/defaults/bash/init
index f3fff3f..78c342d 100644
--- a/defaults/bash/init
+++ b/defaults/bash/init
@@ -1,5 +1,5 @@
 eval "$(rbenv init - bash)"
 eval "$(nodenv init -)"
 eval "$(zoxide init bash)"
-eval "$(zellij setup --generate-auto-start bash)"
+# eval "$(zellij setup --generate-auto-start bash)"
 source /usr/share/doc/fzf/examples/key-bindings.bash
```

**Comment by dhh** [comment]
Oh great! Then it probably is worth switching over. Wonder if it's specifically an nvidia issue. Anyone else hit it too on something else but nvidia?

**Comment by stramec** [comment]
Yep @dhh exactly the same error on boot, fresh install with Nvidia 4080. Zellij (and eza) are throwing errors. Everything else looks to work fine.

**Comment by mphalliday** [comment]
Have the same issue on an older desktop with an Nvida 1050 Ti ... no issues with my AMD framework. Loving this project @dhh 😍

**Comment by dhh** [comment]
Should be fixed now. Run "omakub update" and restart the terminal.
